name: CI/CD Frontend

on:
  push:
    branches:
      - deploy
    paths:
      - 'front_despacho/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar credenciales de AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag y push a ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: front-despacho 
        IMAGE_TAG: latest
      run: |
        cd front_despacho
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Deploy automático en EC2 (SSM)
      env:
        INSTANCE_ID: ${{ secrets.EC2_FRONTEND_INSTANCE_ID }}
      run: |
        aws ssm send-command \
          --instance-ids "$INSTANCE_ID" \
          --document-name "AWS-RunShellScript" \
          --parameters 'commands=[
            "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
            "docker pull ${{ secrets.ECR_REGISTRY }}/front-despacho:latest",
            "docker stop frontend || true",
            "docker rm frontend || true",
            "docker run -d -p 80:80 --name frontend ${{ secrets.ECR_REGISTRY }}/front-despacho:latest"
          ]' \
          --comment "Desplegando el Frontend"
